version: "3.9"
services:
  cache:
    image: redis:latest

  app:
    build: .
    command: python manage.py run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - SOUL_API_REDIS_HOST=cache
      - SOUL_API_DATABASE_URL=sqlite:////etc/soulapi/app.db
    volumes:
      - ./test-volume-db:/etc/soulapi
    depends_on:
      - cache

