"""change table date string

Revision ID: 482635edc200
Revises: 98227d5c2e56
Create Date: 2021-02-26 18:40:12.738221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482635edc200'
down_revision = '98227d5c2e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
